### ISSUE TITLE
DataProviders#crossProduct Iterable support

### ISSUE THREAD

**Issue by rpost** [TNG/junit-dataprovider#103]
Can we add `Iterable` support for `com.tngtech.java.junit.dataprovider.DataProviders#crossProduct` arguments?

**Comment by aaschmid** [comment]
Hi @rpost, 

for sure, it's a good idea. Do you already have an implementation you can share via PR?

Cheers,
Andreas

**Comment by aaschmid** [comment]
And which version are you using (it's not clear from above FQMN)? Is it ok to implement it in v2.0 (or v2.1 respectively)?

**Comment by rpost** [comment]
Currently I'm still using 1.12.0. I can prepare PR, give me a few days.

**Comment by aaschmid** [comment]
Hi @rpost, 
I am ready to implement this features but have the following question:
* Do you want to `crossProduct` two `Iterable<?>` or two `Iterable<Iterable<?>>`?
Cheers,
Andreas

**Comment by rpost** [comment]
I'd suggest to support both options, method arguments would be two `Iterable<?>` and then inside the method depending on given `Iterable` parameter type do the right thing (?)
