### ISSUE TITLE
Regression v.1.11.0 -> 1.12.0 ?

### ISSUE THREAD

**Issue by codecholeric** [TNG/junit-dataprovider#104]
Yes, I know, I'm a late adopter, but I just tried to upgrade the JUnit DataProvider to the actual version (I had 1.10.0), and realized, that my tests were suddenly failing:

```
initializationError FAILED
    java.lang.Exception: No valid dataprovider found for test 'my_test' using the default resolver. By convention the dataprovider method name must either be equal to the test methods name, have a certain replaced or additional prefix (see JavaDoc of class com.tngtech.java.junit.dataprovider.internal.DefaultDataProviderMethodResolver or is explicitely set by @UseDataProvider#value()
```

In earlier times it was possible, to define a test in a base class and then reuse that test with different data providers in subclasses (I know, that might not be the way to go, but it did work in earlier versions).
Example:

```
public abstract class BaseTest {
    @Test
    @UseDataProvider("data")
    public void some_test(Object input) {
    }
}
```

```
@RunWith(DataProviderRunner.class)
public class ChildTest extends BaseTest {
    @DataProvider
    public static Object[][] data() {
        return testForEach(new Object());
    }
}
```

I've narrowed it down to 1.11.0 -> 1.12.0, with 1.11.0 this test runs, with 1.12.0 the test fails with the mentioned exception.
I just wanted to know, if this was just a breaking change (I couldn't find anything in the release notes though), or a regression by accident?

**Comment by aaschmid** [comment]
Thanks @codecholeric for this issue. I will have a look during the next days or is it more urgent?

**Comment by aaschmid** [comment]
Can reproduce the issue. Unfortunately, I haven't had a test case for this scenario as I have never really thought about writing a test like this.

@codecholeric: Is it possible that you migrate to v2.0 such that it is sufficient to fix it there?

**Comment by aaschmid** [comment]
While fixing this issue, I also had to realize that this is quite hard to fix with v1.* as it requires a lot of API changes ...

**Comment by codecholeric** [comment]
I wanted to migrate to 2.0 anyway, so I have no problem, if it only works there :wink: 
And it's not urgent, I've downgraded to 1.11 again, and for the moment everything works.
I could also probably write it in a different way, just concat all data in one test class, instead of creating multiple subclasses with partial data, so that it would work with 2.0.

**Comment by aaschmid** [comment]
Note: a potential workaround would be specifiying the location of the test explicitely (if you do not have to many cases....)
