### ISSUE TITLE
Improve documentation of integration with Spring

### ISSUE THREAD

**Issue by Airblader** [TNG/junit-dataprovider#109]
See the documentation of [junitparams](https://github.com/Pragmatists/junitparams-spring-integration-example#alternative-way-to-start-spring-context). There's a better way to integrate with Spring than writing your own test runner.

Also, the custom runner implemented in the tests has a typo in its name (Sprin_t_…).

**Comment by aaschmid** [comment]
Hi @Airblader, thanks for this issue and your comments. I adjusted the https://github.com/TNG/junit-dataprovider/wiki/Tips-and-Tricks page and fixed the typo.

Fine for you?

**Comment by Airblader** [comment]
Yes, thanks!
