### ISSUE TITLE
Does it include testng @Factory annotation functionality?

### ISSUE THREAD

**Issue by rohitgargfzr** [TNG/junit-dataprovider#110]

**Comment by aaschmid** [comment]
Hi @rohitgargfzr, 

currently junit-dataprovider does not support the features of TestNGs `@Factory` annotation. Instead, you can combine JUnit Jupiters [nested tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested) and `@BeforeAll` annotation for a nested test class with junit-dataprovider or JUnit Jupiter Parameterized Tests to achieve similar results. 

What is you use case? Do you have an example using TestNG such that I can provide an example using JUnit5 and junit-dataprovider?

Cheers,
Andreas

**Comment by aaschmid** [comment]
Any answers on this @rohitgargfzr?

**Comment by aaschmid** [comment]
Closing because of no response to this. Please don't hesitate to reopen.
