### ISSUE TITLE
Unable to run specific test using mvn commandline

### ISSUE THREAD

**Issue by praveenc79** [TNG/junit-dataprovider#111]
## Overview

 DataProviderRunnerWithSpring  does not seem to support selectively running test from a testclass.

For example, In my project I have test - call TestClass and a specific test call test 1
@RunWith(DataProviderRunnerWithSpring.class)
@ContextConfiguration(classes = IntegrationTestConfiguration.class)
public class TestClass {

 @UseDataProvider(value = TestDataProvider.USER, location = TestDataProvider.class)
    @Test
    public void test1(String userId) {
....
        }

  @Test
    public void test2() {
....
        }
}

- ( ) **Question.** 

Now if I run test as follows (using sure-fire plugin):--

mvn -Dtest=TestClass#test1 test 

It does not pickup test1

mvn -Dtest=TestClass#test2 test 

will work absolutely fine

Do you have any thoughts on this? Is this a new feature request ?

**Comment by aaschmid** [comment]
Hi @praveenc79,

thanks for your issue. Unfortunately, I cannot reproduce the issue. Therefore some questions:

* Which version of `mvn` do you use? (`mvn --version`)
* Which version of `surefire-plugin` do you use? (see `pom.xml` or build log)
* Which version `junit-dataprovider` and `spring-test` do you use? (`mvn dependency:tree`)

Use Maven (v3.5.2 with surefire-plugin v2.17) on branch [issue111-single-dataprovider-test-mvn-cmd-line](https://github.com/TNG/junit-dataprovider/tree/issue111-single-dataprovider-test-mvn-cmd-line) from folder `junit4` with a zsh:

```
# works without Spring
mvn -Dtest=\*JavaAcceptanceTest#testAddWithoutDataProvider clean test
mvn -Dtest=\*JavaAcceptanceTest#testIsEmptyString clean test
mvn -Dtest=\*JavaAcceptanceTest#testIsEmptyString\* clean test

# works with Spring
mvn -Dtest=\*SpringAcceptanceTest#testCreateGreetingDataProvider clean test
mvn -Dtest=\*SpringAcceptanceTest#testCreateGreetingNoDataProvider clean test
mvn -Dtest=\*SpringAcceptanceTest#testCreateGreeting\* clean test
```

In comparision use Gradle (v4.6) from repoistory `root` folder:
```
# does not work without Spring
./gradlew junit4:integTest --tests \*JavaAcceptanceTest.testIsEmptyString

# does not work with Spring
./gradlew junit4:integTest --tests \*SpringAcceptanceTest#testCreateGreetingDataProvider

# works without Spring
./gradlew junit4:integTest --tests \*JavaAcceptanceTest.testAddWithoutDataProvider
./gradlew junit4:integTest --tests \*JavaAcceptanceTest.testIsEmptyString\*

# works with Spring
./gradlew junit4:integTest --tests \*SpringAcceptanceTest#testCreateGreetingNoDataProvider
./gradlew junit4:integTest --tests \*SpringAcceptanceTest#testCreateGreeting\*
```

**Comment by aaschmid** [comment]
The problem is the missing `\*` before `JavaAcceptanceTest` such that the command must be
```
mvn -Dtest=\*JavaAcceptanceTest#testIsEmptyString clean test
```
Otherwise you can also use the full class name:
```
mvn -Dtest=DataProviderJavaAcceptanceTest#testIsEmptyString clean test
```

**Comment by praveenc79** [comment]
You are absolutely correct @aaschmid !!! I was confused by the total number of tests being run with those. When I closely looked at the test it shows runs for various data set. 

It does not work in our project though. I will continue to work on that.

**Comment by praveenc79** [comment]
I am closing issue.

**Comment by aaschmid** [comment]
Thx @praveenc79. If you have any further questions or issues, don't hesitate to open an issue.
