### ISSUE TITLE
Memory leak through DataProvider?

### ISSUE THREAD

**Issue by codecholeric** [TNG/junit-dataprovider#116]
In my current project we use the Maven Surefire Plugin (2.18.1) together with JUnit 4 to run a vast number of `DataProvider` test classes (> 5000). I've noticed that with the default settings all data from all `@DataProvider` methods is kept in memory for the whole run. As far as I understand the flow is something like

1) Surefire determines it can execute all x classes eagerly (`JUnitCoreWrapper`) and thus creates one `Request` for those x classes

2) The `Computer.serial()` determines it should create a `Suite` for all those classes

3) `Suite` in turn holds a reference to all `runners`and fills it with all `@RunWith` it can find on the classes (i.e. a lot of `DataProviderRunners` in our case)

4) `DataProviderRunner` holds a reference to `List<FrameworkMethod> computedTestMethods` which in turn can contain `DataProviderFrameworkMethod`

5) `DataProviderFrameworkMethod` on computation fills its `Object[] parameters` from `@DataProvider`

All those references are hard, so data generated by `@DataProvider` will not be garbage collected and stay in memory for the whole further test run.

I don't know who's at fault here (I would have expected JUnit to create a `Runner` on the fly to execute a single test class and throw that instance away once not needed anymore) but my chances for a fix seem best here :wink:

One quick way I can think of would be to add

```
@Override
protected Statement classBlock(final RunNotifier notifier) {
    return new Statement() {
        @Override
        public void evaluate() throws Throwable {
            try {
                DataProviderRunner.super.classBlock(notifier).evaluate();
            } finally {
                releaseReferenceToCachedMethodsToAllowGarbaceCollection();
            }
        }

        private void releaseReferenceToCachedMethodsToAllowGarbageCollection() {
            computedTestMethods = null;
        }
    };
}
```

to `DataProviderRunner`. What are your thoughts about this?

**Comment by aaschmid** [comment]
thanks @codecholeric, I soon have some vacations and will consider this there :-)
If it is more urgent, don't hesitate to tell this.

**Comment by aaschmid** [comment]
I created a fix and a snapshot version, see https://oss.sonatype.org/content/repositories/snapshots/com/tngtech/junit/dataprovider/junit4-dataprovider/2.5-SNAPSHOT/. Would you like to test it @codecholeric?

For Gradle:
```gradle
  repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
  }
  // ...
  dependencies {
    // ...
    testCompile group: 'com.tngtech.junit.dataprovider', name: 'junit4-dataprovider', version: '2.5-SNAPSHOT'
    // ...
  }
```

For Maven:
```xml
  <repositories>
    <repository>
      <id>sonatype-snapshots</id>
      <name>Sonatype Snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    </repository>
  </repositories>
  <!-- ... -->
  <dependencies>
    <!-- ... -->
    <dependency>
      <groupId>com.tngtech.junit.dataprovider</groupId>
      <artifactId>junit4-dataprovider</artifactId>
      <version>2.5-SNAPSHOT</version>
    <dependency>
    <!-- ... -->
  </dependencies>
```

**Comment by codecholeric** [comment]
I couldn't try the fix in our project yet, one thing I have noticed though is that my suggestion might have been a little short-sighted.
Because I've tried the fix in a little example project and I've noticed that it might also be a problem, that `DataProviderRunner` creates all test data on construction.
For example IntelliJ seems to initialize all runners necessary to run the tests in advance, i.e. `computeTestMethods(..)` is called for every test to be run before any `classBlock` is evaluated.
Our concrete problem will still be solved by the fix I think, because it was created by "shady" usage of the data provider (packing large amounts of data into a data point during test execution). But as far as I can see the basic problem, that all test data of all tests will be created in one shot, is still there.
I think the only way to solve this would be to create the data in the beginning of the `classBlock` or similar and perform validation only on statically available information.
I don't know if you want to invest resources in the "old" JUnit 4 support though :wink:.
If you would basically be interested in this refactoring, I could try to do it during my next holiday (June/July). Don't know if it would cause other problems of course, to delay the creation of the test data.

**Comment by aaschmid** [comment]
After reconsidering this issue, I am not sure if it is possible to solve properly.

As already discussed, all the tests are executed at "startup" in order to be able to filter them and get / display the tests to be executed in the build tool / IDE. Therefore I also need to initialize the dataproviders in order to gather all the test cases...

I can release the created and no longer used dataproviders in order to free the acquired heap but this does only help a little.

If you are still interested in testing my beta version above, don't hesitate to reopen this issue.
