### ISSUE TITLE
Compatibilty with junit-jupiter-engine 5.4.0 or higher

### ISSUE THREAD

**Issue by geoffreyharding** [TNG/junit-dataprovider#118]
*Version*: junit-dataprovider 2.4

*Description*: When using jupiter-engine version **5.4.0** or higher with junit-dataprovider, there are compilation and runtime errors.

*Repro Steps*:
- Replace junit-dataprovider\junit-jupiter\pom.xml with the attached pom.xml file.
[pom.xml.txt](https://github.com/TNG/junit-dataprovider/files/3352355/pom.xml.txt)
- java.version : 11 or 1.8 (doesn't matter)
- maven-compiler-plugin : 3.8.0
- maven-surefire-plugin : 3.0.0-M3
- junit-jupiter-engine : 5.4.0
- Run "mvn clean test" from the junit-dataprovider\junit-jupiter folder.

Compilation will fail with errors:
```
[ERROR] /E:/git/junit-dataprovider/junit-jupiter/src/main/java/com/tngtech/junit/dataprovider/UseDataProviderInvocationContextProvider.java:[160,115] incompatible types: org.junit.platform.engine.ConfigurationParameters cannot be converted to org.junit.jupiter.engine.config.JupiterConfiguration
```

If you use the precompiled JARs for junit-dataprovider 2.4 with jupiter-engine version 5.4.0 or higher, you will get the following errors when running tests:
```
java.lang.NoSuchMethodError: org.junit.jupiter.engine.extension.ExtensionRegistry.createRegistryWithDefaultExtensions(Lorg/junit/platform/engine/ConfigurationParameters;)Lorg/junit/jupiter/engine/extension/ExtensionRegistry;
```
Or:
```
java.lang.IncompatibleClassChangeError: Method org.junit.jupiter.engine.extension.ExtensionRegistry.createRegistryWithDefaultExtensions(Lorg/junit/platform/engine/ConfigurationParameters;)Lorg/junit/jupiter/engine/extension/ExtensionRegist
```

*Workaround*:
Downgrade junit-jupiter-engine to 5.3.0.

**Comment by aaschmid** [comment]
Thanks for pointing this out @geoffreyharding. I can reproduce it and I will have a look at it.

**Comment by aaschmid** [comment]
Found a fix but unfortunately this will cause incompatibility with < 5.4.0 and I like backwards campatibility ;-)

**Comment by geoffreyharding** [comment]
for junit-jupiter-engine 5.4+ support we will consider migrating from junit-dataprovider to junit-jupiter-params.

**Comment by aaschmid** [comment]
Sounds a good step IMO. All the best for doing it :-)
I would be curious about a quick report about do's and don'ts as well as pitfalls if you don't mind :-)

**Comment by aaschmid** [comment]
As the junit-team changed the API again with 5.5.0 I prefer creating a new version for 5.5.0 and skipping 5.4.0 such that there is no junit-dataprovider version supporting 5.4.0. What do you think @geoffreyharding?
