### ISSUE TITLE
Wiki pom.xml dependency shows older version

### ISSUE THREAD

**Issue by jaypatel512** [TNG/junit-dataprovider#127]
## Overview

When going through [wiki page](https://github.com/TNG/junit-dataprovider/wiki/Getting-started#maven), I accidentally used older version of your dependency. Either we should update that for every release, or replace it with meta tag `<latest version here>` or similar.

<img width="817" alt="Screen Shot 2020-05-11 at 1 21 03 PM" src="https://user-images.githubusercontent.com/1309895/81596795-4c1d9b00-938a-11ea-9031-b377b56dd56e.png">

## Deliverables

- [ ] Update wiki with appropriate dependency version you want people to recommend

**Comment by aaschmid** [comment]
Thanks for pointing out @jaypatel512. I fixed the cases on the mentioned page

**Comment by jaypatel512** [comment]
@aaschmid I had to include below dependency for it to really work. Not sure if the groupId is valid in wiki!

```xml
    <dependency>
      <groupId>com.tngtech.junit.dataprovider</groupId>
      <artifactId>junit4-dataprovider</artifactId>
      <version>2.6</version>
      <scope>test</scope>
    </dependency>
```

**Comment by aaschmid** [comment]
You are right. thanks for pointing out.
