### ISSUE TITLE
How to use junit-dataprovider with powermock

### ISSUE THREAD

**Issue by zzkyeee** [TNG/junit-dataprovider#133]
I want to use both junit-dataprovider and powermock, but @Runwith only one class.

**Comment by aaschmid** [comment]
Yes, _junit4_ only allows one `@RunWith` and the _junit-dataprovider_ requires one - I tried to change but it is not possible to get rid of it. However _powermock_ seems to provide a `@Rule`, see https://github.com/powermock/powermock/wiki/powermockrule.

Does that help?

**Comment by aaschmid** [comment]
@zzkyeee If you have any further questions, don't hesitate to reopen this issue but for now I will close it as there is no further response on an issue which seems to be unsolvable due to JUnit4s architectural constraints :-(
