### ISSUE TITLE
Separate test data completely from test code in junit-dataprovider

### ISSUE THREAD

**Issue by zlnick** [TNG/junit-dataprovider#43]
Hi guys, should it be a good feature if we separate test data from hard coded test?

So far I found that we can use junit-dataprovider to ease the pain to write test fixtures. 
While in field, when we are trying to improve code coverage, we are usually faced of much more test fixtures and test oracles than test steps, right? 

So if we can help testers to easily try a lot of test data (including both test input and expected output) and keep the test code as simple as possible, it may help. That may be especially useful in data driven tests (DDT).

For example, if we can write a test class as below:

//We will need runners to execute parameterized tests
@RunWith(XmlParameterizedRunner.class)  
//We may need class level or method level annotations to define parameter sources
 @ParameterizedTest(inputPath = "D:/eclipseSpace/putMyth/src/test/resources/testInput/")  
 public class DemoPOJOServiceTest{         
      private final DemoPOJOService pojoService = new DemoPOJOService();  
        
      @Test  
      // also possiblly we'll need annotations to differentiate PUTs from traditional unit tests 
      @ParameterizedMethod  
      public void testCreate(DemoPOJO pojo,boolean expected) throws Exception{  
           Assert.assertTrue(expected == pojoService.create(pojo));  
      }  
        
      @Test  
      @ParameterizedMethod  
      public void testUpdate(DemoPOJO pojo){  
           Assert.assertTrue(pojoService.update(pojo));  
      }  
       
      @Test  
      @ParameterizedMethod  
      public void testCompare(DemoPOJO basePOJO, DemoPOJO cmpPOJO, boolean expected){  
           Assert.assertTrue(false==pojoService.compare(basePOJO, cmpPOJO));  
      }  
 }  

If we can introduce test data from outside sources such as file system or db, the tests would be much neater.

Of course, to do that, we will need several things:
1. dedicated test runner
2. a set of annotations
3. a set of embedded test resource regulation (file, db, etc.)

What do you think?

**Comment by aaschmid** [comment]
Hi @zlnick,

thanks for your issue. Have you had a look at https://github.com/TNG/junit-dataprovider/wiki/Features#access-frameworkmethod-in-dataprovider. Here is at least a possibility to implement this. 
Would this help you? IMHO this could be your start point. 

I could further think about a custom ```Runner``` using custom annotations etc. to create the data automatically (i.e. using a generic ```@DataProvider``` method which is just reading some annotations on the test method! However, I am not sure if it is possible to provide a default structure for the external test data which does not require heavy customizing! Do you have any preferences?

Does that already help you?

Cheers,
Andreas

**Comment by zlnick** [comment]
Hi @aaschmid 

Thank you for your reply.

Yes, with the use of user defined ```DataProvider``` loading data from file or DB can partly solve this problem. 

The reason why I'd like external test data is when I'm testing DAOs or other service methods, if we can use the POJOs as test parameters, the test code will be very neat and short. Otherwise the codes to compose POJOs will take a considerable part and reduce the readability.

To load external test data, I think XML2OBJ libraries such as **XStream** may be helpful. Since:
1. XML is structured and hierarchical hence it can be used to record the value of the parameters even when the parameters are objects instead of primitive types
2. I would assume that when we are writing unit tests, necessary **TYPEs** should be fixed. Then we can use programs to general XML elements to represent object fields, which may later be used by testers. 

Actually I've wrote a little code before to load a XML file into tests. If you are interested, you may have a look at:
http://zlnick79.blogspot.jp/2014/08/putmyth-junit-put-toy-to-run.html (you may also check the other blogs under topic **A parameterzied unit testing enhancement for JUnit**)

In these codes, I'm using a structure like:

    1:  <TestClass className="SomeClassName">  
    2:       <testMethods>  
    3:            <ParameterizedTestMethod methodName="someMethod">  
    4:                 <scenarios>  
    5:                      <TestScenario name="ScenarioName">  
    6:                           <parameters>  
    7:                                <TestParameter parameterName="someParameter">  
    8:                                     <parameter class="ParameterClassName">  
    9:                                          <fieldname>FieldValue</fieldname>  
    10:                                     </parameter>  
    11:                                </TestParameter>  
    12:                           </parameters>  
    13:                      </TestScenario>  
    14:                 </scenarios>  
    15:            </ParameterizedTestMethod>  
    16:       </testMethods>  
    17:  </TestClass> 

AS soon as we can use tools to generate the parameter fields part of this doc(line 7~11), this structure can be delivered to the testers to guild them writing their test data.

Another problem is that if we can really do this, will this feature be useful to the testers? What do you think?

**Comment by janschaefer** [comment]
Hi @zlnick,

I think it should be pretty straightforward to implement this using the feature https://github.com/TNG/junit-dataprovider/wiki/Features#access-frameworkmethod-in-dataprovider as mentioned by @aaschmid above. You simply have your parameters in some file (XML or JSON maybe) and load that file in the method annotated with `@DataProvider`. You can then transform the content of the file into POJOs and put them into an `Object[][]` array. These POJOs can then be used as parameters of your test method.

Best regards,
Jan

**Comment by aaschmid** [comment]
Hi @zlnick, 

I agree with @janschaefer and think you could easily use the mentioned feature for it. By hiding all the XML processing stuff in some base class your code would be clear and easy to read. As testing is a really wide area and everybody preferring different test data locations, I am still neither sure nor convinced to implement a certain feature. I much more prefer having some open framework which everybody can enhance his-/herself for his/her special needs.

Futhermore, I prefer having my test data in the same place as my test code (at least an abstraction of it). Therefore, I prefer to use Builders (e.g. you can use https://github.com/mkarneim/pojobuilder to automatically create builders for your pojo). Then you can easily build some custom test framework with test that are easy to read and change.

```
    @Test
    public void testPutToMap() {
        final long id = anyId();

        // Given:
        Article article = any($validArticle().withId(id));

        // When:
        underTest.put(id, article);

        // Then:
        assertThat(underTest).containsKey(id);
    }
```
Whereby ```anyId()``` generates a random ```id```, ```any()``` executes ```$builder.build```, ```$validArticle``` builds an article with all required fields and returns an ```ArticleBuilder```. ````underTest``` is just a ```Map``` and ```assertThat``` is from ```org.fest.assertions.api.Assertions```.

Kind regards,
Andreas

**Comment by zlnick** [comment]
Hi, @aaschmid @janschaefer

Thank you guys for your comments and tips.
I agree that tester's will appreciate different locations of their test data and indeed there are differences with the amount of data between tests. 
Your comments make sense. Since this feature is not difficult to implement, we can leverage the implementation to the testers.


___________
Best wishes,
Nick
