### ISSUE TITLE
Filtering does only work if test description starts with test method name

### ISSUE THREAD

**Issue by aaschmid** [TNG/junit-dataprovider#48]
This is a follow up issue to #47.

The bug described above is now fixed with commit 4c7f43f. Can you please describe your use case such that I can decide if it is worth to fix the filtering of tests for formats like %p[0]?

**Comment by spaceCamel** [comment]
Hi @aaschmid,
I'm testing a class used to calculate components of a price (net, tax, commission, etc.) from other parameters. The format I use contains the "given" and "expected" values and an additional UUID used to identify the test-case (auto-generated test-case index does not match the CSV file line number I'm using as input, so I added a UUID to avoid confusion).
In short my use-case is to show the explicit context of a failing test to whoever will look at the logs. So I added all the method parameters in the format string.
This is my format string: `@DataProvider(format = "%m | Case %i: net_premium=%p[0], commission_rate=%p[1], ipt_rate=%p[2], commission_load=%p[3],  gross_premium=%p[4], (case_uuid=%p[5])")`

**Comment by aaschmid** [comment]
Hi @spaceCamel,
thanks for your replay. This scenario should work perfectly using version [1.10.0](https://github.com/TNG/junit-dataprovider/releases/tag/v1.10.0) as your test names start with ```%m``` (= test method name). Unfortunately, IntelliJ IDEA does not support that format for running a single test with specific arguments. Eclipse instead does support this!
So, can you confirm that this is working and do you need me to implement anything here?

**Comment by spaceCamel** [comment]
@aaschmid it works! Thanks!
Regarding something to implement... I have an idea.
It would be nice if `junit-dataprovider` could auto-generate "parameter_name=value" pairs using reflection.
As you see I put in my format string "... net_premium=%p[0], commission_rate=%p[1], ..." and so on. Each is just repeating parameter-name and parameter-index of the test-method, and I had to maintain it updated while developing the test.
If there an option, say "%pn[0..n]", automatically expand to the list of "parameter_name=value" pairs I would have picked that one.
Thanks again,
Alessandro

**Comment by aaschmid** [comment]
Hi @spaceCamel, 
this is a very nice idea which you can easily try yourself using a custom placeholder, see https://github.com/TNG/junit-dataprovider/wiki/Features#customize-test-method-name. This should easily work extending ```com.tngtech.java.junit.dataprovider.internal.placeholder.ParameterPlaceholder``` and use the provided context ```method``` and its parameters, e.g. ```method.getParameters()[0].getName()```. The parameter name however, is as far as I know just available if your code has been compiled with the correct options.

**Comment by aaschmid** [comment]
@spaceCamel, any updates on this or any further help needed?

**Comment by spaceCamel** [comment]
Hi @aaschmid,
I haven't got a change to work on the auto-generation of method description.
On the other hand I did no run into any issue after upgrading to 1.10.
I'll let you know if anything changes.
Thanks!

**Comment by aaschmid** [comment]
I consider that as "done". Please reopen if you have any further issues on that.
