### ISSUE TITLE
Reduce verbosity in @UseDataProvider/@DataProvider

### ISSUE THREAD

**Issue by nikowitt** [TNG/junit-dataprovider#54]
Hi there,
from what I see, when I want to use @DataProvider and @UseDataProvider, I
have to define a value in @UseDataProvider that refers to the name to a static @DataProvider annotated method.

I think this is a good spot where convention over configuration could be optionally used, e.g. supplying a blank default value in @UseDataProvider's value and then to check if there is a @DataProvider method that starts with a prefix + the test method name eg

```
@DataProvider
public static Object[][] data_render_grid_fields() {
(...)
}

@UseDataProvider
@Test
public void render_grid_fields(String userName, Class<?> gridName) {
(...)
}
```
It's only a detail, but less configuration is always better :)

Best regards,
Niko

**Comment by aaschmid** [comment]
This would indead be a good place to use convention over configuration. Can we maybe get this into version 2.0. For 2.0 I would also like to change the packages and maybe also the artifact name such that we have some kind of breaking changes there. (Still have to clarify that internally ...) But this would than also be a good point to use convention over configuration at some more points! And also we maybe could implement some more of your good requests (which do not fit that well into the current approaches of v1.x.

Does this sound good to you?

**Comment by nikowitt** [comment]
This sounds very nice. Of course, now I'm curious whethere there is some roadmap about the release of 2.0 (1 week? 1 month? 6 months?) ;)

**Comment by aaschmid** [comment]
If you further questioning the features and code like you do (don't get me wrong I really appreciate it), I would say one or two month, even if I am not able to spend so many time on this open source project right now ...

**Comment by nikowitt** [comment]
It's perfectly fine, I don't expect any of my improvement suggestions to be implemented - I just want to share the feedback and if you decide that (some of) it is not worth implementing it it's also fine for me as long as the attention has been raised.

**Comment by aaschmid** [comment]
Another idea here is to be able to choose the dataprovider using code completion. The only possibility I can think of would be using an annotation preprocessor which generates some constants. This is another "dependency" and IntelliJ could cause problems with this because it does not acutally compile code for every change, as Eclipse does. Maybe we can integrate that as an optional possibility, the same as the above mentioned convention over configuration!

**Comment by aburmeis** [comment]
As the data provider ant tests methods always have different signatures (test method with parameters and data provider without) it would be a easy to use the same name by convention.

**Comment by aaschmid** [comment]
@nikowitt : I really like your ideas but currently there is absolutely no time left which I can invest into a major refactoring and release of the dataprovider. Sorry, so you have to wait until we will find anybody implementing it or until I get more time.

@aburmeis you are absolutely right and I really like the convention over configuration approach :-)

**Comment by nikowitt** [comment]
No problem, the changes I made in my fork that I published as pull request are currently sufficient.

Arne's idea is really nice - I will check the code today and see if I can implement this as this will also streamline our test code. If it works, I will also provide a pull request.

**Comment by nikowitt** [comment]
I've committed the changes, but I seem to have messed up the formatting, so I don't create a pull request here. Please check the second commit.

For my requirement, I only had to set a default blank value in @UseDataProvider and to adapt getDataProviderMethod(FrameworkMethod testMethod) in the DataProviderRunner.

```
	FrameworkMethod getDataProviderMethod(FrameworkMethod testMethod) {
		if (testMethod == null) {
			throw new IllegalArgumentException("testMethod must not be null");
		}
		UseDataProvider useDataProvider = testMethod.getAnnotation(UseDataProvider.class);
		if (useDataProvider == null) {
			return null;
		}

		TestClass dataProviderLocation = findDataProviderLocation(useDataProvider);
		for (FrameworkMethod method : dataProviderLocation.getAnnotatedMethods(DataProvider.class)) {
			if (!"".equals(useDataProvider.value()) && method.getName().equals(useDataProvider.value())) {
				return method;
			} else if ("".equals(useDataProvider.value())) {
				if (method.getName().equals(testMethod.getName()) && method.getReturnType().equals(Object[][].class)) {
					return method;
				}
			}

		}
		return null;
	}
```

Best regards.
Niko

**Comment by aaschmid** [comment]
I know introduced the following convention:

     * ```@DataProvider``` annotated method with the explicitly given annotation value
     * ```@DataProvider``` annotated method which name equals the test method name
     * ```@DataProvider``` annotated method which prefix 'test' is replaced by 'dataProvider'

Is that find for you?

**Comment by nikowitt** [comment]
Sounds great, so as soon a solution for #52 is found, I can switch back to the official releases :)

**Comment by aaschmid** [comment]
Thanks for the fast comment, updated mine above a bit, though.
