### ISSUE TITLE
Provide constants for @DataProvider splitBy default value and "null" string

### ISSUE THREAD

**Issue by nikowitt** [TNG/junit-dataprovider#55]
Hi there,

in order to be able to use constants consistently,the "," used by default in @DataProvider's splitBy and the "null" string that is used in conversion should be provided as a constant somewhere.

Best regards,
Niko

**Comment by aaschmid** [comment]
As this are already the defaults, where would you like to use it?

**Comment by nikowitt** [comment]
I'd like to use this constant in the @DataProvider values. Currently, I have to define an own constant value - we are not using plain strings value like
 ```
@DataProvider({"a,b,c"})
 ```
but
 ```
@DataProvider({ "a"+_+"b"+_+"c"})
 ```
 where _ = ",", but this of course has to be placed somewhere else, although this belongs to @DataProvider itself from a logical point of view.

This of course is a really tiny suggestion, but I'd like to share every feedback that is related to the usage of JGiven/DataProvider in our company :)

**Comment by aaschmid** [comment]
Ok, but this would made the code much less readable I guess. I can provide of course a constant. Let a be an ```_```, though, would not make the code very clear IMHO. And let it be something like ```COMMA``` would generate much more required typing effort ...

The only case where I would see a benefit is to use it because of generating something.

**Comment by nikowitt** [comment]
I must confess that in some cases, the readability can suffer when using the constant, but in some cases (especially when several parameters are used that requires to split the string across a new line or when constant values are used anyways), it also can help to improve the readability.
