### ISSUE TITLE
Ignore case for enum strings

### ISSUE THREAD

**Issue by nikowitt** [TNG/junit-dataprovider#58]
Hi there,
currently, enum values to be converted from strings require uppercase strings. This could be done automatically in the code without throwing any exception:
```
Enum result = Enum.valueOf((Class<Enum>) enumType, str.toUpperCase());
```
Best regards,
Niko

**Comment by aaschmid** [comment]
I am not sure if I want to do this by default as "ENUM_VALUE" is then treated equally to "enum_value" which are actually two different enum values ...

**Comment by nikowitt** [comment]
I think about 99,5% of all enums are written uppercased and the equal treatment only applies to enums that both have got a lowercased and an upper cased value with the same name. Maybe then it makes sense to perform the upper case check as a fall back when the first case sensitive check does not work.

**Comment by aaschmid** [comment]
Hm .. . but if you say that 99.5% of all enums are written uppercased, what is the business case for ignoring the case while converting. I think that this is rather confusing ...

**Comment by nikowitt** [comment]
The business case is that in many cases (at least in our environment), there exist other constants that correspond an enum value, but in small letters (since they are given in camel case). In the tests, when I use the plain dataprovider, I want to use the already existing constant values.

**Comment by nikowitt** [comment]
Keeping your comment in mind, my current change now looks like

```
private Object convertToEnumValue(String str, Class<?> enumType) {
		return convertToEnumValue(str, enumType, false);
	}
	
	private Object convertToEnumValue(String str, Class<?> enumType, boolean upperCase) {
		String value;
		if(upperCase) {
			value= str.toUpperCase();	
		} else {
			value= str;
		}
		 
		try {

			@SuppressWarnings({ "rawtypes", "unchecked" })
			Enum result = Enum.valueOf((Class<Enum>) enumType, value);
			return result;

			} catch (IllegalArgumentException e) {
			if(upperCase) {
				//no match even when uppercased
				throw new IllegalArgumentException(String.format(
						"'%s' is not a valid value of enum %s.", value,
						enumType.getSimpleName()));	
			} else {
				//try again uppercased...
				return convertToEnumValue(str, enumType, true);
			}
			
		}
			
		}
	}
```
This preserves the ability of even having mixed mode enums with e.g. an enum "VALUE" and "value".

**Comment by aaschmid** [comment]
Hi @nikowitt, I am still not convinced because IMHO this is too much magic. @janschaefer what do you think?
I could image having some option in ```@DataProvider``` which ignores case for enums, classes and other senseful types. What do you think?

Cheers,
Andreas

**Comment by nikowitt** [comment]
An ignoreCase param indeed would increase transparency, I like this idea pretty much.

**Comment by aaschmid** [comment]
Implemented, see above. Just not sure how to name the property. Any better suggestions @nikowitt?

**Comment by nikowitt** [comment]
Sounds fine to me.
Regards, NIko
