### ISSUE TITLE
Buggy Eclipse behaviour when object's toString() implementation contains a new line and is used in @DataProvider

### ISSUE THREAD

**Issue by nikowitt** [TNG/junit-dataprovider#59]
Hi there,

I'm currently using @DataProvider with $$, $ more frequently. When the toString() in an object that is used in the data provider contains (more than some) new line(s) (\n) and is executed via JUNIT 4 in Eclipse, the following behaviour can be observed:

- when a test fails with a specific dataset, I cannot explicitely call that dataset again, Eclipse tells me that the "input type of the launch configuration does not exist".
![failure](https://cloud.githubusercontent.com/assets/1472328/10390303/0892e336-6e78-11e5-8414-fdc5a3d26224.png)

- when the whole test class is executed, JUNIT does not stop, the green/red bar never appears, even though I can see the everything is done via console.

As soon as I remove the new lines in the toString() implementation, everything works fine.

**Comment by aaschmid** [comment]
Hm ... we have already got that issue with #42 and I thought it is resolved ...

**Comment by nikowitt** [comment]
The main difference is that I don't get an Eclipse exception, everything is fine according to the console.

Am 10. Oktober 2015 02:38:40 MESZ, schrieb Andreas Schmid <notifications@github.com>:

**Comment by nikowitt** [comment]
Also interesting, as far as I remember this only happens when a specific number of new lines in a toString is exceeded. It worked in a test case when I removed some \n, but not all. If it helps I can try to narrow that down next week.

**Comment by aaschmid** [comment]
Would be nice to get more information but don't hurry as I have currently no time to fix it ... :-(

**Comment by nikowitt** [comment]
This is how I can easily reproduce this.
```
	static class SimpleObject {
		@Override
		public String toString() {
			StringBuilder b = new StringBuilder();
			for (int i = 0; i < 1; i++) {
				b.append("Line " + i + "\n");
			}
			return b.toString();
		}

	}

	@DataProvider
	public static Object[][] loop() {
		return $$($(new SimpleObject()));
	}

	@Test
	@UseDataProvider("loop")
	public void test_infinite_loop(SimpleObject o) {
		assertEquals(7, o.toString().length());
	}
```
Test works in this config, when I change
```
for (int i = 0; i < 1; i++) {
```
to
```
for (int i = 0; i < 2; i++) {
```

the test does not stop.
