### ISSUE TITLE
Ignoring single datapoints

### ISSUE THREAD

**Issue by moritzp** [TNG/junit-dataprovider#60]
We like to write tests like integration tests and such upfront and usually they're even on separate tasks. So if someone grabs that task he now usually "ignores" the new datapoint by commenting it and adding a TODO or something like that. It'd be nice if the junit-dataprovider would offer something like @Ignore for single datapoints.

**Comment by janschaefer** [comment]
You can do that by using the `Assume` class from JUnit and call `Assume.false` for the cases you want to ignore

**Comment by aaschmid** [comment]
To be honest I currently have no good idea how to get this done smoothly besides using the already mentioned ```Assume```s.

@moritzp Besides the above I could image to create a special "column" with a ```boolean``` or constant ```enum``` saying ```IGNORE``` or ```RUN```. This column has to be mentioned with the ```@DataProvider``` annotation as a number which column it would be. The column itself will not go to the test method itself and the test method will not be executed but stated as ignored!

This could also easily be done by yourself with the current version, just let the column got to the test method and use ```Assume``` there.

I am sure if this is a good feature to go to the junit-dataprovider itself. What about the column if the feature is implemented? Do you want to remove it or do you keep it which makes your dataprovider more verbose?

**Comment by aaschmid** [comment]
As I have no further idea of solving this, I will close this issue. Please do not hesitate to reopen as soon as you have new information / new ideas or a solution which requires some adjustements to the junit-dataprovider.

**Comment by aaschmid** [comment]
Maybe we can implement some special treatment of an built-in enum, e.g. ```DataProviderAssumption``` which values ```TODO```, ```IGNORE```, ```RUN```, ```DONE``` or so ...

**Comment by aaschmid** [comment]
@moritzp any opinions?

**Comment by moritzp** [comment]
Sorry for coming back late! 
I'm not a big fan of the assume solution, since we'd have to pass another argument to every method and check on it etc. Having a more generic way which is implemented within the library would be great. E.g. something like your idea of passing a well-defined enum value and wrapping each test method into a library method which encapsulates the enum treatment.

**Comment by aaschmid** [comment]
Agreed to your first point, but for the other solution you also would need to have another column ...
Or do you something different in mind?

**Comment by aaschmid** [comment]
Thinking more detailed about it, I am just struggling about a name for the enum ... I could also imagine to create a custom annotation with ```ElementType.LOCAL_VARIABLE``` which has to be put on a local variable within the dataprovider method. This can than be put as the first column / cell (maybe a stupid idea ...)

Another idea (which I don't like that much) is to that you define the row numbers to be ignored on as a field in the ```@DataProvider```, e.g. ```@DataProvider(ignoreRows = { 3, 5, 8 })```

Here same questions about the implementation:

* Would you just put ```IGNORE``` as first column for every row  to be ignored? Or also ```RUN``` for others?
* Do you think that something like ```TODO``` would be nice if it will run the test but set the test case to ignored if it fails? So you get the logs for the test but it will not fail the build?
* Should we provide this for ```String``` dataproviders as well?

More question will come as soon as they come to my mind. I am looking forward to your answers!

**Comment by aaschmid** [comment]
@moritzp any updates / suggestions on this?

**Comment by aaschmid** [comment]
Issue will be closed because no response from the reporter for over one year ...
Implementation ideas are documented above but it will break a lot of backwards compatibility ...
