### ISSUE TITLE
[Eclipse] DataProvider using custom types

### ISSUE THREAD

**Issue by CrystalMethod** [TNG/junit-dataprovider#62]
Are there any known limitations when using the data provider regarding custom types in conjunction with Eclipse? (other then int, boolean, String..) We have a lot of unit tests passing custom types (business objects like User, Offer - that are often very complex) to the test methods. All tests pass (of course only if there is no error) but the Eclipse JUnit plugin is still running. The Infinitest Eclipse plugin does not have a problem with that.

**Comment by nikowitt** [comment]
Maybe this is the cause?
https://github.com/TNG/junit-dataprovider/issues/59

**Comment by aaschmid** [comment]
Hi @CrystalMethod, 
I just know about the bug mentioned by @nikowitt above. If this is not the case, can you try provide a custom placeholder according to https://github.com/TNG/junit-dataprovider/wiki/Features#customize-test-method-name by maybe skipping the complex business object ```toString()``` representations and try it again?
Cheers,
Andreas

**Comment by CrystalMethod** [comment]
Ok, using ``@DataProvider(format="...")`` really helps. So we can close this issue here. We will try to rework the "problematic" dataproviders in a way to use simple types or customize the formatting of complex business objects.

**Comment by aaschmid** [comment]
HI @CrystalMethod, thanks for clarification and updating this issue. Feel free to open a new one if you have more information or general suggestions for solving your problem :-)
