### ISSUE TITLE
Combination of string based @DataProvider and @UseDataProvider

### ISSUE THREAD

**Issue by nikowitt** [TNG/junit-dataprovider#63]
Hi there,

in our security tests, there are several methods that look like this:
```
	@Test
	@DataProvider({
			ENABLED_QUOTATION_AND_STARTED_ENDED_PUBLISHED_RFQ,
			ENABLED_QUOTATION_AND_NOT_STARTED_NOT_ENDED_PUBLISHED_RFQ,
			ENABLED_QUOTATION_AND_STARTED_NOT_ENDED_PUBLISHED_RFQ,
			DISABLED_QUOTATION_AND_STARTED_NOT_ENDED_PUBLISHED_RFQ,
			DISABLED_QUOTATION_AND_NOT_STARTED_NOT_ENDED_PUBLISHED_RFQ,
			ENABLED_QUOTATION_AND_STARTED_NOT_ENDED_NOT_PUBLISHED_RFQ
	})
	public void validate_access_for_buyer_for_not_related_rfq(boolean isQuotationEnabled, boolean hasRfqStarted, boolean hasRfqEnded,
			boolean isPublished)
			throws Exception {
		(...)
	}
```

As string arrays are not supported in annotations, it would be great if there would be the possibility to extract string based dataproviders into a separate method. Otherwise, a custom string processing is required.

Regards,
Niko

**Comment by aaschmid** [comment]
Hi @nikowitt, I am sorry but do not get what you mean... ```String[]``` are for sure allowed in annotations. That is actually what the ```@DataProvider``` uses.
If possible due to data security reasons, maybe you could provide a more comprehensive example of how you would like to have your test look like.

**Comment by nikowitt** [comment]
String[] are allowed, but a string constant isn't, I cannot provide a public static final String[] CONSTANT in an annotation, I have to assemble the array manually with multiple strings as stated above.

The constant "ENABLED_QUOTATION_AND_STARTED_ENDED_PUBLISHED_RFQ" e.g. consists of "true, true, false, false". I could use the @DataProvider/@UseDataProvider here, but since I want to use the already supplied constant here, I'd have to perform the string --> object conversion myself.

For instance, I cannot do

```
@DataProvider
public static Object[][] data() {
return $$($(ENABLED_QUOTATION_AND_STARTED_ENDED_PUBLISHED_RFQ),
          $(ENABLED_QUOTATION_AND_NOT_STARTED_NOT_ENDED_PUBLISHED_RFQ),
          $(ENABLED_QUOTATION_AND_STARTED_NOT_ENDED_PUBLISHED_RFQ),
          $(DISABLED_QUOTATION_AND_STARTED_NOT_ENDED_PUBLISHED_RFQ),
          $(DISABLED_QUOTATION_AND_NOT_STARTED_NOT_ENDED_PUBLISHED_RFQ),
          $(ENABLED_QUOTATION_AND_STARTED_NOT_ENDED_NOT_PUBLISHED_RFQ));
    }

@Test
@UseDataProvider("data")
    public void validate_access_for_buyer_for_not_related_rfq(boolean isQuotationEnabled, boolean hasRfqStarted, boolean hasRfqEnded,
            boolean isPublished)
            throws Exception {
        (...)
    }
```

Instead, I need to supply a split method that converts the comma separated string based TRUE/FALSE values to 4 boolean values that they fit the test method signature.

**Comment by aaschmid** [comment]
Hm ... I see your problem now. I just don't see benefits according to use a single constant for every argument. This would even be much better readable with a ```// @formatter:off``` block:

```
@DataProvider
public static Object[][] data() {
return $$(
          $(ENABLED_QUOTATION, STARTED,           ENDED,          PUBLISHED_RFQ),
          $(ENABLED_QUOTATION, NOT_STARTED, NOT_ENDED, PUBLISHED_RFQ),
          $(ENABLED_QUOTATION, STARTED,          NOT_ENDED, PUBLISHED_RFQ),
          // ...
    }
```
But maybe I don't see the whole picture ...

**Comment by nikowitt** [comment]
The reason why these constants are implemented that whay is that they are reused as the substring of another argument in other tests using a string based @DataProvider and the usage of other @DataProvider/@UseDataProviders woul increase verbosity. The tests are pretty complex :)

**Comment by aaschmid** [comment]
I would suggest having a helper method like ```$``` which actually does the conversion. But maybe it makes sense to always use ```@UseDataProvider``` with that use case and reuse the dataprovider itself?

**Comment by nikowitt** [comment]
Basically this would work, but due to the fact that other tests use the constants as a substring in other params require me to code logic the StringConverter is capable of doing.

Another idea would be to be able to extend @DataProvider annotated method that they can not only use Object[][] as return type, but also String[]. This would be the indicator that string processing/splitting needs to be applied and does not require any further helpers.

**Comment by nikowitt** [comment]
Basically something like
```
@DataProvider
	public String[] dataProvider() {
		return new String[] {
			ENABLED_QUOTATION_AND_STARTED_ENDED_PUBLISHED_RFQ,
			ENABLED_QUOTATION_AND_NOT_STARTED_NOT_ENDED_PUBLISHED_RFQ,
			ENABLED_QUOTATION_AND_STARTED_NOT_ENDED_PUBLISHED_RFQ,
			DISABLED_QUOTATION_AND_STARTED_NOT_ENDED_PUBLISHED_RFQ,
			DISABLED_QUOTATION_AND_NOT_STARTED_NOT_ENDED_PUBLISHED_RFQ,
			ENABLED_QUOTATION_AND_STARTED_NOT_ENDED_NOT_PUBLISHED_RFQ
	};
	}
	
	@Test
	@DataProvider("dataProvider")
	public void validate_access_for_buyer_as_creator(boolean isQuotationEnabled, boolean hasRfqStarted, boolean hasRfqEnded,
			boolean isPublished)
			throws Exception {
		given().logged_in_user(USER_BUYER)
				.and().rfq_where_buyer_is_creator_of_rfq(false);
		givenWhenReadThenCheckAccess(isQuotationEnabled, hasRfqStarted, hasRfqEnded, isPublished, true);
	}
```

**Comment by aaschmid** [comment]
Great idea, I just thought about that as well while implementing the ```String``` dataproviders and it should acutally work :-)

Example:

```
    // @formatter:off
    @Test
    @DataProvider({
            "0, UP",
            "1, DOWN",
            "3, FLOOR",
        })
    // @formatter:on
    public void testOldModeToRoundingMode(int oldMode, RoundingMode expected) {
        // Expect:
        assertThat(RoundingMode.valueOf(oldMode)).isEqualTo(expected);
    }

    @DataProvider
    public static String[] dataProvider() {
        // @formatter:off
        return new String[] {
            "0, UP",
            "1, DOWN",
            "3, FLOOR",
        };
        // @formatter:on
    }

    @Test
    @UseDataProvider("dataProvider")
    public void testOldModeToRoundingMode2(int oldMode, RoundingMode expected) {
        // Expect:
        assertThat(RoundingMode.valueOf(oldMode)).isEqualTo(expected);
    }
```

It's just an undocumented feature but as internally the same logic is used for both cases ...

**Comment by nikowitt** [comment]
Oh great, I didn't expect this to work out of the box. Thanks for pointing this out, this should probably be officially documented :)

Just tested this, works like a charm!

**Comment by aaschmid** [comment]
Oh, it is also already documented, see https://github.com/TNG/junit-dataprovider/wiki/Features#string-syntax :-)

**Comment by nikowitt** [comment]
Brr... I've must have missed it somehow :(

**Comment by aaschmid** [comment]
No worries, the discussion was still worth to remember the feature and find the solution (at least for me) :-)

**Comment by janschaefer** [comment]
Indeed!
