### ISSUE TITLE
Running junit-dataprovider with Maven unable to generate test results

### ISSUE THREAD

**Issue by whypurplishblue** [TNG/junit-dataprovider#65]
I run mvn clean test, everything builds fine, and the tests looks like they get executed from the logs. But at the end when maven generates the test results for the reports I get the following: 

> Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.232 sec - in test.script.junit.TestLoginFailure
> 
> Results :
> 
> Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

If I run the test *without* using junit-dataprovider I will get:

> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.918 sec <<< FAILURE! - in test.script.junit.TestLoginFailure
> testIt2 on testIt2(test.script.junit.TestLoginFailure)(test.script.junit.TestLoginFailure)  Time elapsed: 7.647 sec  <<< FAILURE!
> java.lang.AssertionError
> 	at test.script.junit.TestLoginFailure.testIt2(TestLoginFailure.java:26)
> 
> 
> Results :
> 
> Failed tests: 
>   TestLoginFailure.testIt2:26 null
> 
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

This is what I expected output. Is there any additional things I need to configure?

A snippet for my code as follows: 
`````java
@RunWith(DataProviderRunner.class)
public class TestLoginFailure extends BaseWebDriverTestClass {
     @Test
	@UseDataProvider("data1")
	public void testIt2(String data) {
		Assert.assertTrue(false);
	}
        @DataProvider
	public static Object[][] data1() throws Exception {
		Object[][] data = {{"hello"},{"hello2"}};
		
		return data;
	}
}
`````

**Comment by aaschmid** [comment]
Hi @whypurplishblue, I do not see anything wrong in your code snippet. Though, I cannot reproduce it because I do not know anything about ```BaseWebDriverTestClass```. As I could not found it via searching the internet, I assume it is something custom from your side, isn't it?

**Comment by aaschmid** [comment]
@whypurplishblue any updates on this?

**Comment by aaschmid** [comment]
Will close the ticket until no more response by the reporter. Please don't hesitate to reopen as soon as you have new information to reproduce it! Thanks!
