### ISSUE TITLE
Support List<Object> for 1 parameter tests

### ISSUE THREAD

**Issue by drdamour** [TNG/junit-dataprovider#67]
It's great it supports multiple params...but it's generally overkill for my uses.  I generally have 1 param.  It'd be nice if i could support that simpler syntax such that a provider that returns List<Object> is checked against the test method to see if it has just 1 param, and in that case allow it through.

**Comment by aaschmid** [comment]
Hi @drdamour, I think this is a valuable feature request. Let me think about it some day. I just want to avoid that it can confuse the user. But likely this will make it to the next version ;-)

**Comment by aaschmid** [comment]
It makes the code a bit more ugly because lists content can only be determined at runtime but it works

**Comment by drdamour** [comment]
got around to using this..very nice...but it would be better if it was List<? extends Object> and not just List<Object>

**Comment by aaschmid** [comment]
Opened issue #78 to continue discussion and implement a solution ;-)
