### ISSUE TITLE
Ability to reference multiple data providers

### ISSUE THREAD

**Issue by aaschmid** [TNG/junit-dataprovider#70]
Would such a feature make sense? I would just allow explicitly given dataprovider names, no more convention?

**Comment by aaschmid** [comment]
Still no necessity for this feature?
@theone1984 wasn't you requesting this?

**Comment by theone1984** [comment]
I think we discussed a more generic approach to linking tests to dataproviders like an own resolver class or something like that. What we are doing is more like creating cross products with exceptions ... to reference more data providers would be a start, but a more dynamic way combined with a fallback to the current convention would be really great.

**Comment by aaschmid** [comment]
Hi @theone1984,

I introduced a new feature where you can provide a custom resolver for your dataprovider methods. Hope this helps :-)
