### ISSUE TITLE
Allow additional convention for @DataProvider method name

### ISSUE THREAD

**Issue by PascalSchumacher** [TNG/junit-dataprovider#76]
I think https://github.com/TNG/junit-dataprovider/issues/54 is a great enhancement. :+1: 

Sadly if you do not use test-names starting with "test" you can only use the "method with a name equals the test method name" option. I think it is a bit confusing to have two methods with the same name.

It would be great if "a method with a name equals to the test method name postfixed with dataProvider" option would be allowed, e.g.:

```java
@DataProvider
public static Object[] shouldBeAbleToAddValuesDataProvider() {}

@Test
public static shouldBeAbleToAddValues(int firstValue, int secondValue) {}
```

or at least allow "a method with a name equals to the test method name prefixed with 'dataProvider'", e.g.:

```java
@DataProvider
public static Object[] dataProviderShouldBeAbleToAddValues() {}

@Test
public static shouldBeAbleToAddValues(int firstValue, int secondValue) {}
```

**Comment by aaschmid** [comment]
Hi @PascalSchumacher, 
thanks for pointing this out as not every writes tests as I do :-)
(but MoreUnit works very nicely with test* to jump between method and its test methods, I always prefix with test* ;-) )

Anyhow, I am happy with adding one of the patterns. As I just work with prefixes for now, I would like to also implement the prefix version of your suggestion if you are fine with it.

**Comment by PascalSchumacher** [comment]
Sure, I'm fine with the prefix version. Thanks in advance!

**Comment by aaschmid** [comment]
see also documentation on https://github.com/TNG/junit-dataprovider/wiki/Features#dataprovider-method-name

**Comment by PascalSchumacher** [comment]
Thanks, works great! :+1:
