### ISSUE TITLE
it would be better if it was List<? extends Object> and not just List

### ISSUE THREAD

**Issue by aaschmid** [TNG/junit-dataprovider#78]
see comment on #67

**Comment by aaschmid** [comment]
Another possibility is to support raw ```List``` or ```List<?>``` or everything which is ```Iterable``` and check at runtime. This would at least shorten the code and make it more usefull. Also somebody could then use ```List<Collection<String>>``` if there would just be strings or ```List<CustomType>``` if ```CustomType``` extends ```Iterable```.
Or the corresponding alternative for a single argument :-)

@drdamour what do you think?

**Comment by drdamour** [comment]
yes anything that is iterable would be great

**Comment by aaschmid** [comment]
Hi @drdamour,
even if this took some time it is now implemented and will be release with the next release
