### ISSUE TITLE
Incorrect work with Maven test plugins

### ISSUE THREAD

**Issue by dmaidaniuk** [TNG/junit-dataprovider#80]
When developer write unit test with usage `@UseDataProvider` and try to run it with [maven surefire plugin](http://maven.apache.org/surefire/maven-surefire-plugin/) or [maven failsafe plugin](http://maven.apache.org/surefire/maven-failsafe-plugin/) he will see next results:
```
Results :
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```
However from console logs it looks like that tests are executed, but results were not properly collected. As an additional drawback of this it can happens that failed test also will be not highlighted.

**Comment by aaschmid** [comment]
Hi @dmaidaniuk,

thanks for reporting this. Unfortunately, I am not able to reproduce it. This junit-dataprovider repository itself contains a ```pom.xml``` which executes tests. This is working fine even with just executing some categories etc. In the past there have already been problems executing junit-dataprovider tests using maven.

Can you provide a reproducer somehow or at least some code snippets how I could reproduce this?

Cheers,
Andreas

**Comment by dmaidaniuk** [comment]
Hi @aaschmid ,
Sure, I will prepare small reproducer project and attach it to this issue in next couple days.

**Comment by aaschmid** [comment]
sounds great, looking forward to it

**Comment by dmaidaniuk** [comment]
Hi @aaschmid ,

During preparation of reproducer project it was discovered real source of problem. We mostly use TestNG for writing tests in our multi-module maven project. However for [Apache Camel tests](http://camel.apache.org/blueprint-testing.html) we used JUnit 4 because [TestNG not supported](https://issues.apache.org/jira/browse/CAMEL-6167). Maven test plugins automatically selects which test-framework provider to use based on project's classpath:

http://maven.apache.org/surefire/maven-surefire-plugin/examples/providers.html
http://maven.apache.org/surefire/maven-failsafe-plugin/examples/providers.html

Having both providers (JUnit + TestNG) in the classpath makes the provider selection indeterministic.
Therefore, we have to force "surefire-junit47" as a provider in this particular case.

Hope this information will be useful for other `junit-dataprovider` users.
Issue closed.

Thanks,
Dmytro

**Comment by aaschmid** [comment]
Thanks @dmaidaniuk for clarification and closing the issue :-)
