### ISSUE TITLE
Name of the scenario for each provider iteration

### ISSUE THREAD

**Issue by neoshadybeat** [TNG/junit-dataprovider#83]
I have no idea if right now It's possible to do something like that 

```
class DataTest extends TestCase
{
    /**
     * @dataProvider additionProvider
     */
    public function testAdd($a, $b, $expected)
    {
        $this->assertEquals($expected, $a + $b);
    }

    public function additionProvider()
    {
        return [
            'adding zeros'  => [0, 0, 0],
            'zero plus one' => [0, 1, 1],
            'one plus zero' => [1, 0, 1],
            'one plus one'  => [1, 1, 3]
        ];
    }
}
```

each test will show the scenario of the left side

**Comment by janschaefer** [comment]
Please have a look at https://github.com/TNG/junit-dataprovider/wiki/Features#customize-test-method-name. There are plenty of options to modify the name of the test case.

**Comment by aaschmid** [comment]
Hi @neoshadybeat,

as @janschaefer already pointed out, there are a lot of customizations possible right now. Unfortunately, the specfic naming of test cases is only possible if you us a separate column with a specific format. Does that already answer your question?

Cheers,
Andreas

**Comment by aaschmid** [comment]
Hi @neoshadybeat, 
what language do you use above?
Do you need a solution of this?
Regards,
Andreas

**Comment by aaschmid** [comment]
Hi @neoshadybeat,

is this still an issue? If yes, can you provide an answer to the above question?

Cheers,
Andreas

**Comment by aaschmid** [comment]
Closing this because of no further response from issue creator such that I cannot help any further.
Please don't hesitate to reopen and provide any further information or details.
