### ISSUE TITLE
Support of wildcards in DataConverter.canConvert

### ISSUE THREAD

**Issue by nikowitt** [TNG/junit-dataprovider#86]
Hi there,

is there any specific reason why
DataConverter.canConvert, line 31 is implemented as
```
return Object.class.equals(innerType);
```
instead of
```
return Object.class.equals(innerType) || innerType instanceof WildcardTypeImpl;
```
? This way, lots of type conversions in a dataprovider can be avoided.

Best regards,
Niko

**Comment by aaschmid** [comment]
Hi @nikowitt, 

glad to hear from you and you are still using our junit-dataprovider :-)

No, there is no reason for that besides that I did not think about that case at all. Thanks for that. Am I rude to ask for PR? :-P

Cheers,
Andreas

**Comment by nikowitt** [comment]
Interesting, it seems that with 1.12.0 it already works - with 1.11.0 I had to implement this.

**Comment by aaschmid** [comment]
Hm ... I refactored the logic. But good if it works already :-)
At least it is worth to write a unit test for your case, though.

**Comment by aaschmid** [comment]
Added an addtional test case even if there have already been a lot ...
No release required as it is working with [v.1.12.0](https://github.com/TNG/junit-dataprovider/releases/tag/v1.12.0) already.

Thanks anyway for the feedback :-)
