### ISSUE TITLE
Automatically create subtree when dataprovider is used

### ISSUE THREAD

**Issue by nikowitt** [TNG/junit-dataprovider#88]
Hi there,
do you think that it is possible to introduce subtrees of test per test/dataprovider combination as blogged here?

http://blog.moritz.eysholdt.de/2014/11/new-eclipse-junit-feature-run-subtrees.html

So basically DataProviderRunner needs to be integrated with Parameterized.class somehow (but also preserve the spring runner)

This way, it would be a lot easier to execute multiple tests (as Eclipse does not allow me to rerun multiple selected tests, but only one) and the overview would be increased greatly?

Best regards,
Niko

**Comment by aaschmid** [comment]
Puh, this is a complex issue ...

1. I already tried a lot with having proper trees but this always leads to not double-clickable parents ... and therefore I decided to not do it.

2. JUnit 5 provides a so called hierarchical runner such that this issue might be absolete if #75 is fixed.

3. What other use cases do you have? 
=> It depends heavily on the uses cases how to structure the test cases. At the moment you can run either a single test case, all test cases of one dataprovider or all test cases of a class.

**Comment by nikowitt** [comment]
The main use case is the implementation of security tests. Basically there are always 4 test cases (CRUD) and they are populated with several parameters like
```
public abstract class JAFRelatedToProjectSecurityTest<STAGE extends JAFRelatedToProjectSecurityStage<STAGE, MODEL, USER, PROJECT, CONDITION>, MODEL extends IDatabaseEntity, USER extends TestUser<?>, PROJECT extends TestProject<?>, CONDITION extends TestCondition>
		extends JAFSimpleTestScenario<STAGE> {
(...)
@Test
@UseDataProvider
public void read(Class<MODEL> clazz, USER sampleUser, boolean success, PROJECT project, CONDITION condition) {
	given().logged_in_user_is(sampleUser.getUserName())
			.and().entity_of_$_related_to_project_$(clazz, project, condition);
	when().user_reads_entity();
	then().access_is_$(success);
}
(...)
}
```

The security tests are designed as a template, so all tests extend from this abstract test class and just the data provider is "overridden" (the specific dataprovider shadows the dataprovider in the superclass), as well as some JGiven stage methods. The dataprovider is a complex method that calculates all possible combinations, so it is not unusual that several 100s or 1000s of combinations are produced (I think the biggest read test produces more than 2000 combinations).

As the tests are inherited (so they are not selectable in the implementing class), Eclipse only allows to execute the whole class and then to reexecute a single combination, so e.g. just executing the whole read test forces me to deactivate the create, update and delete test in the super class. Basically, Eclipse should allow the multiple selection and execution of tests. Creating a test/dataprovider tree helps to be able to re-execute a single inherited test and also provides a better overview (the biggest CRUD test in our environment creates almost 9000 test cases).

**Comment by aaschmid** [comment]
Hi @nikowitt, 

I tried again with no proper result. I have no clue about a good solution for this. Even if JUnit5 (alias junit-jupiter) has a lot more possibilities here, the junit-dataprovider will use the `@TestTemplate` and here I also can only provide a display name and no hierarchy... 

Cheers,
Andreas

**Comment by aaschmid** [comment]
Hi @nikowitt,

JUnit5 and also the corresponding JUnit dataprovider implementation (see #75) will provide this hierarchy out-of-the-box. For JUnit4 I have no more ideas of how to implement this without breaking support of IDEs...

What do you think?

Cheers,
Andreas

**Comment by aaschmid** [comment]
Just pushed my first tries from some month ago, to have another backup of it ...

**Comment by aaschmid** [comment]
Closing this issue due to no further response. If I understand this issue correctly, JUnit5 is able to offer what you want. However, JUnit4 lacks of opportunities to achieve grouping dataprovider tests (e.g. within their method names). A workaround would be directly inheriting `ParentRunner` and implementing it step by step manually ...
