### ISSUE TITLE
support Named parameters

### ISSUE THREAD

**Issue by ChristianSchwarz** [TNG/junit-dataprovider#89]
Assume we have a data provider that provides 4  paramters:

```java
@DataProvider(colums={"type","doors","slideDoors","isECar","isHybrid","consumption"})
public static Object[][] cars() {
   return new Object[][]{
        //Name,              Doors,  Slide-Doors,  isE-Car, isHybrid,  Liter/100km
        {"TransporterA",       2,         1,        false,  false,        8}
        {"Van",                3,         1,        false,  true,         7}
        {"CityCar"             2,         0,        true,   false,        0}
   };
}
```

It would be nice to use the same provider for different tests even if we don't want to use all parameters provided.

use case with row-index
```java
@UseDataProvider("cars")
public void sumOfDoors(@Column(1) int doors,
                       @Column(2) int slideDoors,
                       @Column(0) String carType, ){
  //test doors count agains carType
}
```

use case with row-name 
```java
@UseDataProvider("cars")
public void consumpiton(@Column("type") String carType, 
                        @Column("consumption") int literPer100Km){
  //test consumptioncount agains carType
}
```

Edit: I mixed up column and row (not a native speaker),  now it is fixed.

**Comment by aaschmid** [comment]
Hi @ChristianSchwarz,

thanks for the issue. I will think about it but like the idea pretty much. 

Is it some kind of urgent?

Cheers,
Andreas

**Comment by ChristianSchwarz** [comment]
Well, I am writing currently a test were I could take advantage of it! If you can implement the feature within the next hour would be awsome :smile:

**Comment by janschaefer** [comment]
What you can do instead is just write a new data provider function that takes the existing one and filters out all unused columns:

     @DataProvider
     public static Object[][] carsFiltered() {
          return filter(cars, 1, 2);
     }

     public static Object[][] filter(Object[][] data, Integer... columns) {
           return ....
     }

such a function could maybe added to the `DataProviders` class.

Btw. I guess you mean columns and not rows ;-)

**Comment by aaschmid** [comment]
@ChristianSchwarz: First of all I still need think about it and within the next hour will unfortunately not be possible at all. But I will try to come up with a solution until end of next week. 

Meanwhile you could use @janschaefer solution to do not need to rework too much of your code.

Hope this helps.

**Comment by aaschmid** [comment]
@ChristianSchwarz and @janschaefer I have one further question. 

What would be the benefit for instead using the same dataprovider and just ignoring the arguments which are too much?

**Comment by ChristianSchwarz** [comment]
@aaschmid 

> What would be the benefit for instead using the same dataprovider and just ignoring the arguments which are too much?

Sometime you need e.g the first and the last argument out of 3. So this case cant be handled with this approach.

**Comment by aaschmid** [comment]
It depends if the byte code is compiled with some special option (which is by default switched on ...). 

I honestly don't get your case. If you just need first and the last argument out of 3, just ignore the second parameter ... (otherwise you also could have the problem to execute the some test twice because just the second parameter differs ...)

What is your opinion on the two points above?

I rather have to think about the benefits myself ...

**Comment by ChristianSchwarz** [comment]
> If you just need first and the last argument out of 3, just ignore the second parameter

Yes thats my current work around. But i have parameter tests with up to 6 parameters where are only 3 are used. The code becomes unreadable and hard to maintain. Parameters that are not required should be removed to provide clarity of the test.

**Comment by aaschmid** [comment]
Ok, and how to deal with same test cases as  because just ignored / removed parameters differ?

**Comment by aaschmid** [comment]
Hi @ChristianSchwarz,

sorry, for not having more time meanwhile to think about this. I got your arguments and also think about the hard to maintain one. Currently I am not sure if it would be hard to maintain to provide the column name / index using an annotation. 
Is this still an issue as I am honestly undecided if I want to implement this. Is this really an issue you have a lot? I write a lot of tests myself but reusing a dataprovider is a seldom benefit ...

With JUnit 5 (see #75) you can even try to implement it yourself. As soon as I will get the JUnit dataprovider more flexible on paramters vs. arguments count to also use `@ParameterResolver` with dataproviders, I can imagine that this feature could be implemented as well, easily ...

Cheers,
Andreas

**Comment by aaschmid** [comment]
I will close this issue due to no response. If you are unhappy with that, don't hesitate to reopen and ask your questions.
