### ISSUE TITLE
Show test parameter names in test name?

### ISSUE THREAD

**Issue by PascalSchumacher** [TNG/junit-dataprovider#90]
At least with java 8 it could be possible to display the name of the test method parameters (instead of the index) in the test name. For example display `testDevision[dividend:10, divisor: 2, quotient:5]` instead of `testDevision[0:10, 1: 2, 2:5]` as test name.

**Comment by aaschmid** [comment]
Hi @PascalSchumacher, the index of the parameter is not used at all at the moment. Only the index of the row is shown. The format of how the test name is shown, can be adjusted via parameter in `@DataProvider`. However, it would make sense to be able to adjust the default somehow properly. 

What do you think?

**Comment by aaschmid** [comment]
Ah yes, for names I think we need to extend the framework that this are provided while resolving the `Placeholder`s but I can do this of course.

**Comment by PascalSchumacher** [comment]
I think displaying the parameter names would be more informative that the index of the row, so having the option to enable this would be nice.

But I have no clue how junit-dataprovider is implemented. So no hard feelings if you just close this because it's not possible/too much work/doesn't fit the vision. :-)

**Comment by aaschmid** [comment]
Ok, I will implement it but not sure yet if this is a version 2.0 feature as it is breaking a some externally available interfaces ... I will think about this in detail as soon as I have some spare time left :-)

**Comment by PascalSchumacher** [comment]
Thanks!

**Comment by aaschmid** [comment]
As this is a breaking change for version 1.x, I will implement it with 2.x ...

**Comment by aaschmid** [comment]
As I am not willing to include a byte code reading library, this features will only be supported with Java 8 using `-parameter` compiler flag in dataproviders JUnit Jupiter implementation. The first draft is already available :-)

**Comment by PascalSchumacher** [comment]
Thanks. 👍

So I just have to migrate to junit-dataprovider 2.0, compile with the `parameter` flag and use the `na` placeholder in the format string and it should work? Or am I missing something?

**Comment by aaschmid** [comment]
This is the plan but the feature branch is not merged to master yet and therefore not part of v2.0-SNAPSHOT. You can fork the repo and create your own SNAPSHOT version, though. I will first have to write some unit tests to ensure that it is working properly for all circumstances...

**Comment by aaschmid** [comment]
My current idea according to the format would be a comma-separated list which items would be `${parameterName}=${argument.toString()}` (simplified).

@PascalSchumacher do you have another idea / desired format because above you wrote something about `:`?

**Comment by PascalSchumacher** [comment]
Imho `parameterName1=parameterValue1, parameterName2=parameterValue2` format is fine.

I just wrote `parameterName1:parameterValue1, parameterName2:parameterValue2` above because it is closer to the current (positional) format.

**Comment by aaschmid** [comment]
New version of `2.0-SNAPSHOT` version is now available on "https://oss.sonatype.org/content/repositories/snapshots/", containing also this feature.
