### ISSUE TITLE
Should I expect the dataprovider to run 3x if there are 3 tests?

### ISSUE THREAD

**Issue by BrianJavaJazz** [TNG/junit-dataprovider#93]
I need to generate my data just once before 3 tests are run.  Afterwards, I walk through the data and use each piece for the tests.  For "this" entity type, test these things, then for the next entity type, test the same things, etc.  

But as I increase the number of @Test-annotated tests which are run, the dataprovider will run additional times at startup.  As it is getting the same data, this is unnecessary.   It's possible I have this set up incorrectly. 

Is this expected functionality?  Is there a way to get the data a single time only? 

I saw that issue #87 was similar, but not this exact issue.  

Thank you!

Brian

JDK 1.8.0_121
JUnit 4.12.0
junit-dataprovider 1.12.0
eclipse STS 3.7.3

How about some code!  Here is a simplified version of my test class and a secondary class which holds the data provider generator.  

First, the test driver:

`
@RunWith(DataProviderRunner.class)
public class testdataprovider  {

	protected WebDriver driver;
	protected NgWebDriver ngWebDriver;
	public Map<String, String> createdDataMap;
	public AddPageElements addPageElements;
	public ListPageElements listPageElements;
	private static boolean initialized = false;
	public static LandingPageTestHandler testHandler;
	public TestScriptHandler scriptHandler;
		
	public static Object[][] actualData = null;

	@DataProvider
	public static Object[][] data() {		
		actualData = TestScriptHandler.getGenericsList(testHandler);
		return actualData;       
	}

	@Before
	public void startup() {
		if (initialized == false) {
			scriptHandler = new TestScriptHandler();
			initialized = true;
		}
	}

	@Test
	@UseDataProvider("data")
	public void oOTestCreate(TypeDefinition typedef) {		
		System.out.println("\nTEST 1 " + typedef.getEntityType());
	}

	@Test
	@UseDataProvider("data")
	public void testUpdate(TypeDefinition typedef) {
		System.out.println("\nTEST 2  " + typedef.getEntityType());
	}

	@Test
	@UseDataProvider("data")
	public void testDeactivate(TypeDefinition typedef) {
		System.out.println("\nTEST 3 " + typedef.getEntityType());
	}

}
`

Then, the secondary class which generates the Object[][].  This class logs in to an internal website, get a list of specific items, (the generic list, not a list of generics) then puts them into the typedefObjectArray.  The array is then returned.  

`public class TestScriptHandler {

	public static Object[][] getGenericsList(LandingPageTestHandler testHandler) {
    	
		BasePage basePage = new BasePage();
    		LoginPage logginPage = basePage.getLoginPage();
		WebDriver driver = basePage.getDriver();
		NgWebDriver ngWebDriver = basePage.getNgWebDriver();

		logginPage.goTo()
		.loginAs(basePage.getUsername(), basePage.getPassword());

		testHandler = new LandingPageTestHandler(driver, ngWebDriver, basePage);
		ArrayList<TypeDefinition> genericList = testHandler.getGenericList();
		Object[][] typedefObjectArray = new Object[genericList.size()][1];
		
		for (int i=0; i < genericList.size();  i++) {
			typedefObjectArray[i][0] = (TypeDefinition)genericList.get(i);
		}
		driver.quit();
		return typedefObjectArray;		
	}

}
`

**Comment by BrianJavaJazz** [comment]
Also, if I change the methods to handle strings, then call the following, it work as I expect:  getDataObject is called a single time.  

`	public static Object getDataObject() {			
		return new Object[][] {			
			{ "Entry One" },   
			{ "Entry Two" },
			{ "Entry Three" },    
		};
	}`

Stymied in Seattle.

**Comment by aaschmid** [comment]
Hi @BrianJavaJazz, sorry but I am currently on a business trip and maintaining this in my spare time. I will have a look as soon as possible (at latest on the weekend).
Is that ok?

Cheers,
Andreas

**Comment by janschaefer** [comment]
Maybe I can try to answer the question. I think there is currently no way to tell the JUnitDataProvider runner to not call the data provider method each time. However, you can easily fix this yourself by just storing the results in a static variable and returning the variable once it has been generated. Like in your first example, where you even store the values in a static variable. You could modify that as follows:

     public static Object[][] actualData = null;

     @DataProvider
     public static Object[][] data() {		
            if (actualData != null) {
          	    actualData = TestScriptHandler.getGenericsList(testHandler);
            }
            return actualData;       
     }

**Comment by BrianJavaJazz** [comment]
aaschmid and janschaefer, 

Thank you both for your replies.  janschaefer, that is pretty close to what I implemented just yesterday.  In the external class which handles the data (where the dataprovider gets it's data) I have:

`public static Object[][] preloadedData = null;
...
if (preloadedData == null) {
//go generate it
}
`
In this scenario the data is generated once and returned as many times as needed without the extra logins and generation I had before.  This shaved 15 seconds off of my testing!  janschaefer, your solution is even better.  

Thank you both.  Cheers!

Brian

**Comment by BrianJavaJazz** [comment]
Hello.  Yes, the workaround is fine.  I have no issues with it, and the urgency is no more than average.  My main concern at the time was that a scan for the same data was costing my tests some extra time, but that was the only issue.  

Thank you for your continued communication.  I appreciate it. 

Best regards, 

Brian

**Comment by aaschmid** [comment]
Hi @BrianJavaJazz,

finally I released the new version v1.13.0 containing this fix.

Cheers,
Andreas
