### ISSUE TITLE
Support running as a JUnit Rule instead of a JUnit Runner

### ISSUE THREAD

**Issue by dalewking** [TNG/junit-dataprovider#94]
Not sure it is even possible, but requiring a Junit Runner makes this plugin unusable in any cases where you have to use another runner. Would be awesome if this could run as a JUnit rule instead.

See https://dzone.com/articles/writing-parameterized-tests for an implementation of test parameters using Junit Rule, but it is not as nice in that it doesn't use method parameters.

**Comment by aaschmid** [comment]
Hi @dalewking,

thanks for your issue. I thought really long about it already quite some time ago but unfortunately, JUnit 4 doesn't allow a more "native" integration for junit-dataprovider as a rule. 
The reason: if you want to get a "native" lifecycle and IDE integration as well as parameters for test methods like now, the tests to be executed must be known very soon after the constructor of the used `Runner`. Rules are generated much later almost immediately before execution of the tests.
This prevents you using a rule while keeping the features provided by `BlockJUnit4ClassRunner` without re-implementing it yourself, like integration in the lifecycle methods (`@Before`, `@After`).
If you would re-implement it, still the well working integration for all the IDEs would break as for `@Parameterized` or your example above (e.g. test cases cannot be appear as soon as executed and cannot be not assigned to their classes any more). 
JUnit 5 does better but does not provide a proper extension point (as `@TestFactory` is not well integrated in the lifecycle methods) for additional test case creation, yet (see #75).

So my currently preferred solution would be waiting for JUnit 5 to provide an extension point. The major refactoring implementing `Runner` from scratch would be quite large, as I look at it from a current point of view , for supporting a old / dying framework. Do you have another opinion about that? However, I will keep this issue and will think about it again as soon I will get more spare time once again ... 

What is your use case? For Spring, CDI etc. you can use the workaround described in https://github.com/TNG/junit-dataprovider/wiki/Tips-and-Tricks.

Cheers,
Andreas

**Comment by dalewking** [comment]
My use case is trying to combine data provider with robolectric (using an older version) for parameterized Android unit tests. The robolectric runner is a bit more complicated and its runner actually creates another helper runner. I got close on combining them into a single runner but could not quite get it working. Robolectric has a combined runner for junit parameterized tests, but as you say the fact that you are violating the no parameters rule complicates things quite a bit.

**Comment by aaschmid** [comment]
Hi @dalewking,

can you send you me your tries combining robolectric and junit-dataprovider runner?
I currently do not have a better idea if I don't want to loose other features described above.

Regards,
Andreas

**Comment by dalewking** [comment]
All I have now is my failed attempt to do it with 2.4 which I don't think
can work. I am trying to get our app to work with 3.x but running into many
obstacles including memory leaks that did not occur with 2.4 which means we
run out of memory after about 1400 of our 2800 tests.

**Comment by aaschmid** [comment]
Hi @dalewking,

can you send you me your tries combining robolectric and junit-dataprovider runner?
I currently do not have a better idea if I don't want to loose other features described above.

Regards,
Andreas

**Comment by aaschmid** [comment]
Hi @daleking,
thanks for your quick reply. The question for me is, how can I help you properly? Do you have an idea on that?
Cheers,
Andreas

**Comment by aaschmid** [comment]
Hi @dalewking,
with JUnit5 support (see #75) now in beta test you can run multiple extensions at the same time (if the extension is already available). Is this an option for you?
Cheers,
Andreas

**Comment by dalewking** [comment]
I've moved on to a different employer so this is not a current concern for me, but others may need it.

**Comment by aaschmid** [comment]
Thanks for the quick answer. As this will be supported with JUnit 5 (not as rule but with their equivalent mechanism called "extensions") and as there is no possibility I know providing this with JUnit4 without loosing the possibility to provide a proper test output of all executed methods, I marked this "solved" with coming up version 2.0 JUnit5. Therefore I will close this issue.
