### ISSUE TITLE
Can we used cucumber with junit-dataprovider?

### ISSUE THREAD

**Issue by gaponte1985** [TNG/junit-dataprovider#95]
Can we used cucumber with junit-dataprovider?

**Comment by aaschmid** [comment]
Hi @gaponte1985, 

I am not sure what you mean by that. Cucumber has it's own data tables, see https://cucumber.io/docs/reference#data-tables. But if you want to do BDD with a more developer friendly, fluent API, I can recommend to have a look at JGiven, see http://jgiven.org/. This is also usable with junit-dataprovider out-of-the-box.

Does that help?

Cheers,
Andreas

**Comment by gaponte1985** [comment]
Thanks but not, so I have a data provider and a class runner, so I used 

@RunWith(DataProviderRunner.class )
public class BaseRunner extends FluentCucumberTest {
	@Test
	@UseDataProvider(value = "getParams", location = BrowserComboDP.class)
code 
}

How can I tell my class runner of cucumber that I want to used my dataprovider?

**Comment by gaponte1985** [comment]
when I run my data provider I am getting the value but, my class runner is not running 
<img width="730" alt="screen shot 2017-06-25 at 10 52 47 am" src="https://user-images.githubusercontent.com/996659/27517130-e2291d8c-5994-11e7-8f56-a11e9124a4db.png">

**Comment by aaschmid** [comment]
Hi @gaponte1985,

Unfortunately, JUnit4 is not flexible enough to have multiple runners. The only possibility is to extend one of the runners to create a single new runner. Here is some documentation for Spring and CDI: https://github.com/TNG/junit-dataprovider/wiki/Tips-and-Tricks#dataprovider-for-dependency-injection-frameworks. Maybe this way is also possible for cucumber class runner.

Do you see an opportunity doing that?

**Comment by gaponte1985** [comment]
I dont think this will be useful because in one point going to have multiple class runner of cucumber, the idea was to used junit-dataprovider for this. But thanks, maybe in the future you can add that can support cucumber features

**Comment by aaschmid** [comment]
Hi @gaponte1985, with JUnit5 it will be possible to use multiple Extensions and combine them properly. I am sorry but I don't get your point as cucumber has datatables out of the box, see https://cucumber.io/docs/reference#data-tables. So no need to use junit-dataprovider here IMHO.

**Comment by gaponte1985** [comment]
I was able to do it with extends a class that have 

new TestNGCucumberRunner(getClass()).runCukes();

**Comment by aaschmid** [comment]
Hi @gaponte1985, 
is this still an issue for you?
With JUnit5, see #75 you can have multiple extensions such that you can use JUnit dataprovider and Cucumber in combination (if Cucumber already supports JUnit5 but I think there is an extension out there).
Cheers,
Andreas
