### ISSUE TITLE
Can you get the test method name inside the DataProvider?

### ISSUE THREAD

**Issue by frincutudor** [TNG/junit-dataprovider#96]
Hello ,
I would like to know if there is a way to get the test method name inside the DataProvider.I am working with a xcel and trying to make a single data provider for multiple tests by having the test name on column and comparing them with the test name that is running at a point. Or else i am open to any other ways to make a single data provider.

Thanks very much.

**Comment by aaschmid** [comment]
Hi @frincutudor,

you can retrieve the `FrameworkMethod` within the `@DataProvider` using https://github.com/TNG/junit-dataprovider/wiki/Features#access-frameworkmethod-in-dataprovider. Is this what you need? 

For your Excel idea, you could also have a look at this: (https://github.com/TNG/junit-dataprovider/wiki/Features#custom-dataprovider-method-resolvers) - to not require to implement a `@DataProvider` at all and receive the `FrameworkMethod`s directly. Could that be a solution?

If both or no option, do you have an example? To be honest, though, I think you need to wait for JUnit 5 which is able to receive the test method name within the test method.

**Comment by aaschmid** [comment]
Hi @frincutudor,
do you have any news on this?
With JUnit Jupiter and JUnit Jupiter Parameterized Tests, the dataprovider gets even more exensible. See #75 for any details how you can test this already. 
Cheers,
Andreas

**Comment by aaschmid** [comment]
Closing this because as far as I understood the question, the solution is described above. 
Please don't hesitate to reopen and provide any further information or details.
