### ISSUE TITLE
Usage with Kotlin

### ISSUE THREAD

**Issue by vpratfr** [TNG/junit-dataprovider#97]
I am trying to use your library with Kotlin.

When not inside a companion object, it complains that the provider method is not static (no such concept in the Kotlin language).

When inside a companion object (the way to do static stuff in Kotlin), it complains that it cannot find the method (indeed, it is not anymore in the DataTest class.

Problem: I could not find a way to provide the location as the companion object generated class.

```
@RunWith(DataProviderRunner::class)
class DataTest : UnitTestCase() {

    companion object {
        @DataProvider
        fun testRelativeAngleProvider(): Array<Array<Any>> = arrayOf(
                // @formatter:off
            arrayOf(Data(0),           -1.0f),
            arrayOf(Data(255),      1.0f),
            arrayOf(Data(128),      0.0f)
            // @formatter:on
        )
    }

    @Test
    @UseDataProvider("testRelativeAngleProvider")
    fun testRelativeAngles(data: Data, expected: Float) {
        assertThat(data.relativeValue).isEqualTo(expected)
    }
}
```

Any hint?

**Comment by aaschmid** [comment]
Hi @vpratfr,

sorry for the long delay and thanks for the issue. 
Indeed junit-dataprovider is currently not working with Kotlin :-(

I just tried to fix this quickly but due to the missing concept of `static` it is a bit tricky to do so. Currently I have no good idea how to fix this not breaking the good old Java features such that the best way I could think of, is providing a separate version for Kotlin ...

As I am new to Kotlin I have another questsion which came to my mind: 
What is the reason that you do not use kotlintest Tables (see https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#table). This seems to be a similar feature. 

How urgent is your request?

Cheers,
Andreas

**Comment by aaschmid** [comment]
Hi @vpratfr,

you can ignore my previous post, I found out the solution. Just add a `@JvmStatic` annotation to the companion object function and it plays nicely :-)

Here is my complete example:

```
import com.tngtech.java.junit.dataprovider.DataProvider
import com.tngtech.java.junit.dataprovider.DataProviderRunner
import com.tngtech.java.junit.dataprovider.DataProviders.`$$`
import com.tngtech.java.junit.dataprovider.DataProviders.`$`
import com.tngtech.java.junit.dataprovider.UseDataProvider
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(DataProviderRunner::class)
class DataTest {

    companion object {
        @DataProvider
        @JvmStatic
        fun testRelativeAngleProvider(): Array<Array<Any>> = `$$`(
                // @formatter:off
            `$`( 0,  0,  0),

            `$`( 0,  1,  1),
            `$`( 1,  0,  1),
            `$`( 1,  1,  2),

            `$`( 0, -1, -1),
            `$`(-1,  0, -1),
            `$`(-1, -1, -2),

            `$`( 1, -1,  0),
            `$`(-1,  2,  1)
            // @formatter:on
        )
    }

    @Test
    @UseDataProvider(value = "testRelativeAngleProvider")
    fun testRelativeAngles(a: Int, b: Int, c: Int) {
        assert(a + b == c);
    }
}
```

**Comment by vpratfr** [comment]
Cool. I had not thought about that workaround. Maybe that would be worth mentionning in the documentation (Kotlin support is official in the Android world, so I guess you can expect to get more queries about Kotlin in the near future)

**Comment by aaschmid** [comment]
done, see https://github.com/TNG/junit-dataprovider/wiki/Features#kotlin-support
