### ISSUE TITLE
Provision for run-time annotations

### ISSUE THREAD

**Issue by ag24021987** [TNG/junit-dataprovider#98]
I have 2 tests in my file and both of them have separate data providers providing file paths. I want to be able to run a single test with a single selective file. For that there should be a way of ignoring a @Test based on certain conditions e.g. if the data provider is empty or run-time annotations. If a certain check fails, I should be able to replace my @Test method with something like TestNG has @Test(enabled=false)

**Comment by aaschmid** [comment]
Hi @ag24021987, 

I am not sure if I understand your question correctly. If my answer is not what you expect, maybe you can provide an example to make it clearer for me.

If you want to run one of the two tests, you can just click on the test method and choose "Run As" after right mouse click (at least in Eclipse). If you want to run a single dataprovider row, this can only be done by first running all tests and afterwards select the one you want to rerun. 

Cheers,
Andreas

**Comment by aaschmid** [comment]
Hi @ag24021987, 
any news on this?
Cheers,
Andreas

**Comment by aaschmid** [comment]
Closing this because of no further response from issue creator such that I cannot help any further.
Please don't hesitate to reopen and provide any further information or details.
