### ISSUE TITLE
swapped order of @BeforeClass and @ClassRule

### ISSUE THREAD

**Issue by matonthecat** [TNG/junit-dataprovider#99]
when using the DataProviderRunner, the setup order of class setup methods (@BeforeClass) and fields annotated @ClassRule is exchanged.

I.e. the following code 

```java
@RunWith(DataProviderRunner.class)
public class TestRuleTest {

    @ClassRule
    public static Expensive expensive = new Expensive();

    private static class Expensive implements TestRule {

        @Override
        public Statement apply(Statement base, Description description) {

            System.out.println("classrule execution");
            return base;
        }
    }

    @BeforeClass
    public static void setupClass() {

        System.out.println("BeforeClass execution");
    }

    @Test
    public void testFoo() {

        System.out.println("test execution");
    }
}
```

prints 

`
BeforeClass executionclassrule execution
`
`
test execution
`

whereas without @RunWith(DataProviderRunner.class) it would print

`
classrule execution
`
`
BeforeClass execution
`
`
test execution
`

This means that if I setup a TemporaryFolder class rule, I cannot expect it to be created when my class setup method is reached. Which means, I cannot prepare any files for my tests.

**Comment by aaschmid** [comment]
Hi @matonthecat,

thanks for the issue. Which version are you using? With the newest version I cannot reproduce this issue, but until version 1.10.3 this was an issue introduce with https://github.com/TNG/junit-dataprovider/wiki/Features#beforeclass-support. Since version 1.10.4 I removed this feature because of similar problems you described.

Cheers,
Andreas

**Comment by matonthecat** [comment]
Hi Andreas,

Thank you for the response.

Not sure if this is in fact a duplication. I understand that the other issue you mentioned is about the order of BeforeClass and DataProvider, whereas this one is about the order of BeforeClass w.r.t ClassRule. The former is not my concern.

Would it be possible to keep the ordering of the latter or are they somehow related?

Best
Matthias

**Comment by matonthecat** [comment]
Just saw that this is in fact solved. My last test was somehow having an old version (1.10.0) mixed with the latest version on the class path x-)
